
messages:
  invalid-enchantment: 'Specified enchantment is not valid.'
  invalid-enchantment-level: 'Given enchantment level is too high for this enchantment.'
  incompatible-enchantment: 'This enchantment can not be applied to this item!'
  cant-afford-enchantment: 'You can not afford to purchase this enchantment tier! (Missing: {level})'
reforged-chances:
  bound: 1000
  level-1: 15
  level-2: 40
enchantments:
  level-15:
    - 'dive'
    - 'vision'
    - 'magma'
    - 'haste'
  level-30:
    - 'obsidian'
    - 'feast'
    - 'bounce'
  level-45:
    - 'agility'
    - 'vitality'
    - 'defiance'
    - 'health'
    - 'experience'
    - 'moxie'
    - 'coins'
    - 'reforged'
    - 'resurgence'
combine-costs:
  tier-1: 15
  tier-2: 30
  tier-3: 45
enchantment-item:
  material: 341
  data: 0
  display: '&bCustom Enchantment'
  lore:
    - ' &b* &7Enchantment: &f{enchantment}'
    - ' &b* &7Level: &f{level}'
    - ' &b* &7Applicable: &f{applicable}'
enchantment-format: '{tier-color}{enchantment} {level}' # {tier-name}, {tier}
enchanter:
  rows: 3
  title: '   &8(&4&l!&8)  <Enchanter Menu>  &8(&4&l!&8)'
  items:
    basic:
      level: 15
      material: 340
      data: 0
      slot: 11
      display: '&bBasic Custom Enchant'
      lore:
        - '&7&o(( Left-click to purchase a &f&oBCE &7&o))'
        - ' &3* &7Experience Cost: &b15 Levels'
    advanced:
      level: 30
      material: 340
      data: 0
      slot: 13
      display: '&aAdvanced Custom Enchant'
      lore:
        - '&7&o(( Left-click to purchase an &f&oACE &7&o))'
        - ' &2* &7Experience Cost: &a30 Levels'
    divine:
      level: 45
      material: 340
      data: 0
      slot: 15
      display: '&cDiving Custom Enchant'
      lore:
        - '&7&o(( Left-click to purchase a &f&oDCE &7&o))'
        - ' &4* &7Experience Cost: &c45 Levels'
  background:
    filler:
      material: 160
      data: 7
      display: ''
      lore: ['']
      slots: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]